# Global configuration
---
apigee:
  hosturl: ${managementApiProtocol}://${managementApiDomain}:${managementApiPort}
  apiversion: ${managementApiVersion}
  options: validate
  delay: 3000
  managementUrl: ${managementApiProtocol}://${managementApiDomain}:${managementApiPort}${managementApiPath}
  apigee:
    config:
      options: validate

apigeelint:
  threshold: errorCount
