# Global common configuration
---
apigee:
  hosturl: ${managementApiProtocol}://${managementApiDomain}:${managementApiPort}
  apiversion: ${managementApiVersion}
  options: validate
  delay: 3000
  managementUrl: ${managementApiProtocol}://${managementApiDomain}:${managementApiPort}${managementApiPath}
  config:
    options: create

apigeelint:
  threshold: errorCount
