# Global test profile configurations
---
apigee:
  env: test
  org: ${testOrganization}

${apiproxyName}:
  northbound:
    domain: ${testProxyDomain}
    basePath: ${apiproxyBasePath}
    protocol: ${testProtocol}
    virtualHost: ${testProxyVirtualHost}