# ApiProxy prod profile configuration
---
apigee:
  env: prod
  org: ${prodOrganization}

northbound:
  domain: ${prodProxyDomain}
  port: ${prodProxyPort}
  basePath: ${apiproxyBasePath}
  protocol: ${prodProtocol}
  virtualHost: ${prodProxyVirtualHost}

southbound:
  targetEndpoint:
    successCodes: 2XX
    path: /