# ApiProxy test profile configuration
---
apigee:
  env: test
  org: ${prodOrganization}

northbound:
  domain: ${testProxyDomain}
  port: ${testProxyPort}
  basePath: ${apiproxyBasePath}
  protocol: ${testProtocol}
  virtualHost: ${testProxyVirtualHost}

southbound:
  targetEndpoint:
    successCodes: 2XX
    path: /
